### ISSUE TITLE
MSTestHawks 2.3.2.0 : Unit Test Adapter threw exception: Data source 'Namespace.UnitTest1.Stuff' cannot be found in the test configuration settings..

### ISSUE THREAD

**Issue by jitukg20** [Thwaitesy/MSTestHacks#7]
Hi, 
I Have installed MSTestHawks 2.3.2.0 in Visual studio 10, with .net 4.0 and created a new test project.
I used exactly the same code as you have shown in the Example.
I also have a blank or default App.config in this project.

But the test does not run and it gives the following error :
Unit Test Adapter threw exception: 
Data source 'Namespace.UnitTest1.Stuff' cannot be found in the test configuration settings..

Can you please guide on the solution to this problem.

**Comment by jeroenwalter** [comment]
I had the same problem in VS2013. This was caused because the unit test project is missing the application configuration file app.config. What happens if this file is missing is as follows:
On startup the mstesthack code tries to add the dynamic datasources to the app.config file of the visual studio testrunner. This fails if you have installed Visual studio somewhere in C:\Program files\ because you need administrator rights to write in that folder. If you start visual studio as administrator, it will succeed.
The correct solution is to add an application configuration file app.config to your unit test project.
This should also be fixed in the mstesthack unit test project.
